# WIP current builds are producing greyscale tiles, possibly a bug when compiling against newer libs
FROM maphubs/gdal-node:mapnik-v2.4.1-v8.16.0-v4.2.1 as builder
WORKDIR /app
RUN apk update && \
    apk add --no-cache git python make gcc g++ alpine-sdk util-linux tar unzip python-dev libexecinfo-dev
COPY package.json package-lock.json /app/
RUN npm config set '@bit:registry' https://node.bitsrc.io && \
    npm install --production
RUN npm install gdal --build-from-source --shared_gdal

# Bundle app source
FROM maphubs/gdal-node:mapnik-v2.4.1-v8.16.0-v4.2.1
WORKDIR /app
COPY --from=builder /app .
COPY . .
RUN rm -r node_modules/mapnik &&\
  cp -r /opt/node-mapnik/ node_modules/mapnik
RUN mkdir -p /app/temp
VOLUME ["/app/temp/"]
VOLUME ["/app/logs"]
EXPOSE 4008
# hack to fix lib6-compat path on alpine 3.9+
#RUN cp /lib64/ld-linux-x86-64.so.2 /lib
CMD ["node", "server.js"]